Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Entities;
using Proekt;
using FlightManager.Filters;
using FlightManager.Attributes;

namespace FlightManager.Controllers
{
    public class FlightsController : Controller
    {
        private readonly FlightDbContext _context;

        public FlightsController(FlightDbContext context)
        {
            _context = context;
        }

        // GET: Flights
        public async Task<IActionResult> Index()
        {
            return View(await _context.Flights.ToListAsync());
        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // GET: Flights/Create
        [LoggedUserFilter]
        [AdminFilter]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [LoggedUserFilter]
        [AdminFilter]
        
        public async Task<IActionResult> Create([Bind("LocationFrom,LocationTo,TakeOff,Landing,TypeOfPlane,PlaneNumber,PilotName,CapacityOfPassengers,CapacityOfBusinessClass,Id")] Flight flight)
        {
            //if (flight.Landing < flight.TakeOff)
            //{
            //    ModelState.AddModelError("Landing", "Landing Date needs to be after the Take Off Date!");
            //}
            if (ModelState.IsValid)
            {
                _context.Add(flight);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: Flights/Edit/5
        [LoggedUserFilter]
        [AdminFilter]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights.FindAsync(id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [LoggedUserFilter]
        [AdminFilter]
        public async Task<IActionResult> Edit(int id, [Bind("LocationFrom,LocationTo,TakeOff,Landing,TypeOfPlane,PlaneNumber,PilotName,CapacityOfPassengers,CapacityOfBusinessClass,Id")] Flight flight)
        {
            if (id != flight.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: Flights/Delete/5
        [LoggedUserFilter]
        [AdminFilter]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [LoggedUserFilter]
        [AdminFilter]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flight = await _context.Flights.FindAsync(id);
            _context.Flights.Remove(flight);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlightExists(int id)
        {
            return _context.Flights.Any(e => e.Id == id);
        }
    }
}

Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Entities;
using Proekt;
using FlightManager.Filters;
using System.Net.Mail;
using System.Text;

namespace FlightManager.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly FlightDbContext _context;

        public ReservationsController(FlightDbContext context)
        {
            _context = context;
        }

        // GET: Reservations
        [LoggedUserFilter]
        public async Task<IActionResult> Index()
        {
            var flightDbContext = _context.Reservations.Include(r => r.Flight);
            return View(await flightDbContext.ToListAsync());
        }

        // GET: Reservations/Details/5
        [LoggedUserFilter]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Flight)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations/Create
        public IActionResult Create(int id)
        {
            ViewData["FlightId"] = new SelectList(_context.Flights, "Id", "Id");
            Test.Flight = _context.Flights.FirstOrDefault(f => f.Id == id);
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("FirstName,MiddleName,LastName,Email,Egn,Telephone,Nationality,TicketType")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                reservation.FlightId = id;
                _context.Add(reservation);
                Flight flight = _context.Flights.FirstOrDefault(f => f.Id == id);
                //Test.Flight = flight;

                if (reservation.TicketType == Data.Enums.TicketType.Economy)
                {
                    flight.CapacityOfPassengers--;
                }
                else
                {
                    flight.CapacityOfBusinessClass--;
                }

                //SendEmail(reservation);

                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            ViewData["FlightId"] = new SelectList(_context.Flights, "Id", "Id", reservation.FlightId);
            return View(reservation);
        }

        private static void SendEmail(Reservation reservation)
        {
            string to = reservation.Email; //To address    
            string from = "mhadzhikovakeva@gmail.com"; //From address    
            MailMessage message = new MailMessage(from, to);

            string mailbody = $"Your reservation for flight from {reservation.Flight.LocationFrom} to " +
                $"{reservation.Flight.LocationFrom} is confirmed. Now you can not cancel it!{Environment.NewLine}" +
                $"Ticket is on name : {reservation.FirstName} {reservation.MiddleName} {reservation.LastName}{Environment.NewLine}" +
                $"It is {reservation.TicketType} class{Environment.NewLine}" +
                $"Enjoy your Flight!";
            message.Subject = "Confirmation of flight reservation";
            message.Body = mailbody;
            message.BodyEncoding = Encoding.UTF8;
            message.IsBodyHtml = true;
            SmtpClient client = new SmtpClient("smtp.gmail.com", 587); //Gmail smtp    
            System.Net.NetworkCredential basicCredential1 = new
            System.Net.NetworkCredential("mhadzhikovakeva", "mihi*hadz");
            client.EnableSsl = true;
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.Credentials = basicCredential1;
            client.Send(message);
        }

        // GET: Reservations/Edit/5
        [AdminFilter]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            ViewData["FlightId"] = new SelectList(_context.Flights, "Id", "Id", reservation.FlightId);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminFilter]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,MiddleName,LastName,Email,Egn,Telephone,Nationality,TicketType,FlightId,Id")] Reservation reservation)
        {
            if (id != reservation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(reservation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FlightId"] = new SelectList(_context.Flights, "Id", "Id", reservation.FlightId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        [AdminFilter]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Flight)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AdminFilter]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservations.FindAsync(id);
            _context.Reservations.Remove(reservation);

            Flight flight = await _context.Flights.FirstOrDefaultAsync(f => f.Id == reservation.FlightId);
            if (reservation.TicketType == Data.Enums.TicketType.Economy)
            {
                flight.CapacityOfPassengers++;
            }
            else
            {
                flight.CapacityOfBusinessClass++;
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservations.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlightManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FlightManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (AuthUser.LoggedUser is not null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Flights" asp-action="Index">Make Reservation</a>
                            </li>
                        }

                        @if (AuthUser.LoggedUser is not null)
                        {
                            @if (AuthUser.LoggedUser.IsAdmin)
                            {
                                <li class="nav-item float-nav-right">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservations</a>
                                </li>

                                <li class="nav-item float-nav-right">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Flights" asp-action="Index">Flights</a>
                                </li>
                                <li class="nav-item float-nav-right">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                </li>
                            }

                            <li class="nav-item float-nav-right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Logout</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <div align="right">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                                </div>

                            </li>
                            <li class="nav-item">
                                <div align="right">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Register">Register</a>
                                </div>

                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FlightManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>